services:
  app:
    image: ${DOCKER_USERNAME}/camnect-server:latest
    container_name: camnect-server
    restart: always
    volumes:
      - /mnt/ebs/verifications:/var/app/uploads/verifications
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
        SPRING_PROFILES_ACTIVE: prod
        JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=70.0