services:
  app:
    image: ${DOCKER_USERNAME}/camnect-server:latest
    container_name: camnect-server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    volumes:
      - /etc/camnect/secrets/firebase-admin.json:/var/app/secrets/firebase-admin.json:ro
    environment:
        SPRING_PROFILES_ACTIVE: prod
        JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=70.0
        GOOGLE_APPLICATION_CREDENTIALS: /var/app/secrets/firebase-admin.json

