app:
  auth:
    email-verification:
      expiration-minutes: 30
      mail:
        subject: "CamNecT 이메일 인증번호"
  verification:
    document:
      storage: s3 #local | s3
      storage-dir: /var/app/uploads/verifications
      max-file-size-mb: 10
      max-files: 3
      allowed-content-types:
        - application/pdf
        - image/jpeg
        - image/png
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION:ap-northeast-2}
    prefix: ${AWS_S3_PREFIX:verifications}



spring:
  application:
    name: camnect-server

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/${DB_NAME:camnect}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USER_NAME:camnect}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_USER_PASS:camnect1234}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 실제 이메일 주소
    password: ${MAIL_PASSWORD} # 앱 비밀번호 (2단계 인증 후 발급)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


server:
  port: 8080
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 360000
  refresh-token-expiration-ms: 1209600000